# Generated by Django 6.0.5 on 2026-06-03 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_title', models.CharField(max_length=255)),
                ('compliance_framework', models.CharField(choices=[('ISO_27001', 'ISO/IEC 27001 Global Information Security Standard'), ('SOC_2', 'SOC 2 Corporate Operational Trust Principles')], max_length=30)),
                ('description', models.TextField()),
                ('target_date', models.DateField(help_text='Mandatory fixing deadline (SLA)')),
                ('completion_date', models.DateField(blank=True, help_text='Actual patch deployment timeline', null=True)),
                ('status', models.CharField(choices=[('CRITICAL', 'Critical Risk'), ('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('PATCHED_SECURED', 'Patched & Secured')], default='CRITICAL', max_length=30)),
                ('remarks', models.TextField(blank=True, help_text='Audit and patch deployment log notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
